import { CheckSquare } from "lucide-react";

const scores = [["Client Review Call","95"],["Budget Review","90"],["Strategy Session","80"]] as const;
const automation = [["Notes Generated","25"],["Action Items Created","32"],["Task Asigned","28"],["Follow-up Emails Sent","18"],["CRM Records Updates","22"],["Customer Health Updated","15"]] as const;

export function PriorityAutomation() {
  return <section className="grid gap-4 lg:grid-cols-2">
    <article className="rounded-[12px] bg-white p-6"><h2 className="border-b border-[#E4EAF8] pb-4 text-xl font-medium">Priority Score</h2><h3 className="mt-4 text-base font-medium">Meetings by Priority</h3><div className="mt-3 flex flex-col items-center gap-4 sm:flex-row sm:justify-between"><div className="flex size-[120px] shrink-0 items-center justify-center rounded-[60px] bg-[conic-gradient(#EF4444_0deg_52deg,#F59E0B_52deg_137deg,#10B981_137deg_360deg)]"><div className="flex size-[72px] flex-col items-center justify-center rounded-[36px] bg-white"><strong className="text-base font-medium">87</strong><span className="text-[10px]">Avg Score</span></div></div><div className="space-y-3 text-xs"><p><i className="mr-1 inline-block size-2 rounded-[4px] bg-[#EF4444]" />High(80-100) 42%</p><p><i className="mr-1 inline-block size-2 rounded-[4px] bg-[#F59E0B]" />Medium(50-79) 38%</p><p><i className="mr-1 inline-block size-2 rounded-[4px] bg-[#10B981]" />Low ((0-49) 20%</p></div></div><div className="mt-4 border-t border-[#E4EAF8] pt-4"><h3 className="mb-2 text-base font-medium">Confidence Score</h3><div className="space-y-2">{scores.map(([label,value])=><div key={label} className="flex h-[39px] items-center gap-2 rounded-[8px] bg-[#F5F7FF] pr-2 text-sm"><span className="h-full w-1 rounded-[2px] bg-[#10B981]" /><span className="flex-1">{label}</span><span>{value}</span><span className="rounded-[4px] bg-[#EF4444]/10 px-1 py-0.5 text-[#EF4444]">High</span></div>)}</div></div></article>
    <article className="rounded-[16px] bg-white p-6"><h2 className="border-b border-[#F5F7FF] pb-4 text-xl font-medium">Next - Meeting Automation</h2><div className="mt-4 space-y-2">{automation.map(([label,value])=><div key={label} className="flex h-[37px] items-center gap-2 rounded-[8px] bg-[#F5F7FF] pr-2 text-sm"><span className="h-full w-1 rounded-[2px] bg-[#10B981]" /><CheckSquare className="size-5 text-[#10B981]" /><span className="flex-1">{label}</span><strong className="font-medium">{value}</strong></div>)}</div></article>
  </section>;
}
